[build]
  command = "npm run build"
  commandOrigin = "config"
  publish = "/opt/build/repo/build"
  publishOrigin = "config"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
  redirectsOrigin = "config"
